services:
  nginx:
    image: c3t4r4/laravel:nginx
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html:delegated
    depends_on:
      - php
      - pgsql
    networks:
      - laravel

  pgsql:
    image: postgres:latest
    tty: true
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - listen_addresses='*'
      - -c
      - "host all ${DB_USERNAME} 0.0.0.0/0 scram-sha-256"
    networks:
      - laravel

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - laravel

  php:
    image: c3t4r4/laravel:php-8.2
    volumes:
      - app_data:/var/www/html:delegated
    networks:
      - laravel

  composer:
    image: c3t4r4/laravel:composer
    volumes:
      - app_data:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: ["composer", "--ignore-platform-reqs"]

  npm:
    image: node:lts
    volumes:
      - app_data:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

  artisan:
    image: c3t4r4/laravel:php-8.2
    volumes:
      - app_data:/var/www/html:delegated
    depends_on:
      - pgsql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel

  init-app:
    image: alpine/git
    volumes:
      - app_data:/git-destination
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST_APP}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      GIT_REP: ${GIT_REP}
      GIT_TOKEN: ${GIT_TOKEN:-}
    entrypoint: /bin/sh -c "
      if [ -n \"$$GIT_TOKEN\" ] && [ \"$$GIT_TOKEN\" != \"\" ]; then
      GIT_REP=\"https://${GIT_TOKEN}@$${GIT_REP#https://}\"
      fi && \
      git clone $$GIT_REP /git-destination || true && \
      cp /git-destination/.env.example /git-destination/.env && \
      sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=$$DB_CONNECTION/' /git-destination/.env && \
      sed -i 's/^DB_HOST=.*/DB_HOST=$$DB_HOST/' /git-destination/.env && \
      sed -i 's/^DB_PORT=.*/DB_PORT=$$DB_PORT/' /git-destination/.env && \
      sed -i 's/^DB_DATABASE=.*/DB_DATABASE=$$DB_DATABASE/' /git-destination/.env && \
      sed -i 's/^DB_USERNAME=.*/DB_USERNAME=$$DB_USERNAME/' /git-destination/.env && \
      sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=$$DB_PASSWORD/' /git-destination/.env"
    networks:
      - laravel

volumes:
  app_data: null
  postgres_data: null

networks:
  laravel:
    driver: overlay
