services:
  app:
    image: c3t4r4/laravel:laravel-12
    working_dir: /var/www/app
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 5s
      timeout: 20s
      retries: 10
    #ports:
    #  - "80:80"
    volumes:
      - spmobile_laravel:/var/www/app
    depends_on:
      - pgsql
      - redis

  app-worker:
    image: c3t4r4/laravel:laravel-12
    working_dir: /var/www/app
    command: php artisan queue:work --timeout=0
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'artisan queue:work' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - spmobile_laravel:/var/www/app
    depends_on:
      - pgsql
      - redis
      - app

  app-scheduler:
    image: c3t4r4/laravel:laravel-12
    working_dir: /var/www/app
    command: bash -c 'while true; do php artisan schedule:run --no-interaction; sleep 60; done'
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'artisan schedule:run' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - spmobile_laravel:/var/www/app
    depends_on:
      - pgsql
      - redis
      - app

  pgsql:
    image: postgres:17
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: America/Sao_Paulo
      POSTGRES_INITDB_ARGS: "--locale=en_US.UTF-8"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - spmobile_postgres:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - listen_addresses=*

  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 2s
      retries: 10
    restart: unless-stopped
    volumes:
      - spmobile_redis:/data

volumes:
  spmobile_laravel:
    name: spmobile_laravel
  spmobile_postgres:
    name: spmobile_postgres
  spmobile_redis:
    name: spmobile_redis