services:
  app:
    image: c3t4r4/laravel:laravel-12
    ports:
      - "80:80"
    volumes:
      - laravel_volume:/var/www/app
    networks:
      - laravel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  pgsql:
    image: postgres:17
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: America/Sao_Paulo
      POSTGRES_INITDB_ARGS: "--locale=en_US.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - listen_addresses=*
    networks:
      - laravel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - laravel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  laravel_volume:
    external: true
    name: laravel_volume
  postgres_data:
    external: true
    name: postgres_data
  redis_data:
    external: true
    name: redis_data

networks:
  laravel:
    external: true
    name: laravel
